/***************
* Enumerations *
****************/
#[derive(Copy)]
pub enum lcb_http_status_t {
    LCB_HTTP_STATUS_CONTINUE = 100,
    LCB_HTTP_STATUS_SWITCHING_PROTOCOLS = 101,
    LCB_HTTP_STATUS_PROCESSING = 102,
    LCB_HTTP_STATUS_OK = 200,
    LCB_HTTP_STATUS_CREATED = 201,
    LCB_HTTP_STATUS_ACCEPTED = 202,
    LCB_HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION = 203,
    LCB_HTTP_STATUS_NO_CONTENT = 204,
    LCB_HTTP_STATUS_RESET_CONTENT = 205,
    LCB_HTTP_STATUS_PARTIAL_CONTENT = 206,
    LCB_HTTP_STATUS_MULTI_STATUS = 207,
    LCB_HTTP_STATUS_MULTIPLE_CHOICES = 300,
    LCB_HTTP_STATUS_MOVED_PERMANENTLY = 301,
    LCB_HTTP_STATUS_FOUND = 302,
    LCB_HTTP_STATUS_SEE_OTHER = 303,
    LCB_HTTP_STATUS_NOT_MODIFIED = 304,
    LCB_HTTP_STATUS_USE_PROXY = 305,
    LCB_HTTP_STATUS_UNUSED = 306,
    LCB_HTTP_STATUS_TEMPORARY_REDIRECT = 307,
    LCB_HTTP_STATUS_BAD_REQUEST = 400,
    LCB_HTTP_STATUS_UNAUTHORIZED = 401,
    LCB_HTTP_STATUS_PAYMENT_REQUIRED = 402,
    LCB_HTTP_STATUS_FORBIDDEN = 403,
    LCB_HTTP_STATUS_NOT_FOUND = 404,
    LCB_HTTP_STATUS_METHOD_NOT_ALLOWED = 405,
    LCB_HTTP_STATUS_NOT_ACCEPTABLE = 406,
    LCB_HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED = 407,
    LCB_HTTP_STATUS_REQUEST_TIMEOUT = 408,
    LCB_HTTP_STATUS_CONFLICT = 409,
    LCB_HTTP_STATUS_GONE = 410,
    LCB_HTTP_STATUS_LENGTH_REQUIRED = 411,
    LCB_HTTP_STATUS_PRECONDITION_FAILED = 412,
    LCB_HTTP_STATUS_REQUEST_ENTITY_TOO_LARGE = 413,
    LCB_HTTP_STATUS_REQUEST_URI_TOO_LONG = 414,
    LCB_HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE = 415,
    LCB_HTTP_STATUS_REQUESTED_RANGE_NOT_SATISFIABLE = 416,
    LCB_HTTP_STATUS_EXPECTATION_FAILED = 417,
    LCB_HTTP_STATUS_UNPROCESSABLE_ENTITY = 422,
    LCB_HTTP_STATUS_LOCKED = 423,
    LCB_HTTP_STATUS_FAILED_DEPENDENCY = 424,
    LCB_HTTP_STATUS_INTERNAL_SERVER_ERROR = 500,
    LCB_HTTP_STATUS_NOT_IMPLEMENTED = 501,
    LCB_HTTP_STATUS_BAD_GATEWAY = 502,
    LCB_HTTP_STATUS_SERVICE_UNAVAILABLE = 503,
    LCB_HTTP_STATUS_GATEWAY_TIMEOUT = 504,
    LCB_HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED = 505,
    LCB_HTTP_STATUS_INSUFFICIENT_STORAGE = 507
}
impl Clone for lcb_http_status_t {
    fn clone(&self) -> Self { *self }
}
impl Default for lcb_http_status_t {
    fn default() -> Self { unsafe { zeroed() } }
}